services:
  redis:
    image: redis:7.4-alpine
    container_name: redis_production
    restart: always
    ports:
      - "${LISTEN_IP:-127.0.0.1}:6379:6379" # Use environment variable for IP
    volumes:
      - redis_data:/data # Persist Redis data in a named volume
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD} # Set a strong password for Redis
      - REDIS_MAXMEMORY=2gb # Limit memory usage to prevent OOM issues
      - REDIS_MAXMEMORY_POLICY=allkeys-lru # Evict least recently used keys when memory is full
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    sysctls:
      - net.core.somaxconn=1024 # Increase the maximum number of connections
    ulimits:
      nofile:
        soft: 65535 # Increase file descriptor limits
        hard: 65535
    security_opt:
      - no-new-privileges:true # Prevent privilege escalation
    logging:
      driver: json-file
      options:
        max-size: "10m" # Limit log size
        max-file: "3" # Rotate logs after 3 files
    networks:
      - redis_network

  pii-api: 
    image: hashwarlock/pii-api:latest
    container_name: pii-api
    restart: always
    ports:
      - "8080:80" # Expose API on host 8080 -> container 80
    networks:
      - redis_network
    environment:
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
      - REDIS_KEY=${REDIS_PASSWORD}
      - REDIS_DB=0
    depends_on:
      - redis
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock

  client-app:
    build:
      context: ./src/client_app
      dockerfile: Dockerfile
    container_name: client-app
    restart: always
    expose:
      - 8000
    ports:
      - "8000:8000" # Use environment variable for IP
    networks:
      - redis_network
    environment:
      - REDPILL_API_KEY=${REDPILL_API_KEY}
      - REDPILL_ENDPOINT=${REDPILL_ENDPOINT}
      - REDPILL_MODEL_NAME=${REDPILL_MODEL_NAME:-}
      - API_URL=http://pii-api
      - TEXTUAL_HOST=0.0.0.0
      - TEXTUAL_PORT=8000
      - TEXTUAL_PUBLIC_URL=http://localhost:8000
      - SESSION_FILE_PATH=/app/sessions/.pii_tee_session
    depends_on:
      - pii-api
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock
      - ./sessions:/app/sessions

networks:
  redis_network:

volumes:
  redis_data: